
# Construccion del Docker-compose
version: '3'
services: 
  test:
    image: edpo1998/backendpython
    environment:
    - HOST=0.0.0.0
    - PORT=4002
    ports:
    - "4002:4002"
# docker-compose build
# docker-compose up -d