version: "3"

services:
  backend:
    image: "diians2302/backend-node-proyecto1semi1"
    container_name: backendNodeJS
    environment:
        PORT: 4200
        DB_HOST: '18.207.227.183'
        DB_PORT: '3306'
        DB_USER: 'root'
        DB_NAME: 'Proyecto1'
        DB_PASSWORD: 'p@ssw0rd'
        AWS_ACCESS_KEY_ID: "AKIA5ORMXYID6CJR6664"
        AWS_SECRET_ACCESS_KEY: "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"
    ports:
      - "4200:4200"
    restart: always