### REGISTER
POST http://localhost:4200/student/register HTTP/1.1
Content-Type: application/json

{
    "user": "Prueba6",
    "email": "prueba6@gmail.com",
    "password": "encriptada",
    "photo": "none"
}

### LOGIN
POST http://localhost:4200/student/login HTTP/1.1
Content-Type: application/json

{
    "name": "Prueba4",
    "password": "encriptada"
}

### SEND REQUEST FRIEND
POST http://localhost:4200/student/addFriend HTTP/1.1
Content-Type: application/json

{
    "id_usuario_f": 3,
    "id_friend_f": 4
}

### ACCEPT REQUEST FRIEND
POST http://localhost:4200/student/aceptFriend HTTP/1.1
Content-Type: application/json

{
    "id_usuario": 4,
    "id_friend": 3
}

### NEW PUBLICATION
POST http://localhost:4200/home/upload HTTP/1.1
Content-Type: application/json

{
    "id_usuario": 6,
    "name": "Archivo 13",
    "file": "Archivo ",
    "visibility": 1,
    "password": "encriptada"
}

### DELETE PUBLICATION
POST http://localhost:4200/home/delete HTTP/1.1
Content-Type: application/json

{
    "id_usuario": 2,
    "name": "Archivo 4",
    "password": "password"
}

### UPDATE PUBLICATION
POST http://localhost:4200/home/edit HTTP/1.1
Content-Type: application/json

{
    "id_usuario": 2,
    "name": "Archivo 4",
    "new_name": "Nombre Cambiado",
    "visibility": 0,
    "password": "password"
}

### GET PUBLICATIONS
POST http://localhost:4200/home/getPublicationsUser HTTP/1.1
Content-Type: application/json

{
    "id_usuario": 7
}
