version: "3"

services:
  database:
    image: "mysql"
    container_name: database
    environment:
        MYSQL_ROOT_PASSWORD: "p@ssw0rd"
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./database:/var/lib/dataMysql  